version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-golangsantri
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_golang
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
